### ISSUE TITLE
Plugin inspiration

### ISSUE THREAD

**Issue by Zales0123** [odiseoteam/SyliusReportPlugin#1]
Hello Odiseo team!

My name is Mateusz, I work in Sylius company and one of my roles is Plugin Curator - I'm responsible for checking out Sylius Plugins that appear in our ecosystem.

I've encountered on this plugin some time ago - I'm really happy, that somebody wants to revive **SyliusReportBundle** as a Sylius plugin, as it was one of my first contributions to Sylius a few years ago. However, I think it would be nice to mention in plugin description that it's highly inspired on past Sylius bundle and component (and by *highly inspired* I mean it's almost all copy-pasted :)). I know we have not been supporting it for the last 2 years, I know it's released under MIT license. I just really believe, that open-source is mostly about mutual respect - and releasing someones work with all author blocks and commits history removed is a little violation of this rule :)

Best regards and have fun with Sylius plugins!

**Comment by odiseoteam** [comment]
Hi @Zales0123, you are right. It was not our intention to hide where this plugin code comes from. Of course we will make the changes that you were suggesting. 

We have been working with the original **SyliusReportBundle** code around one year. First we created this [fork](https://github.com/odiseoteam/SyliusReportBundle) to make support for Sylius 1.0, even we have worked to extend that for some client projects.

We appreciate your recommendation. In Odiseo we believe in open source and in fact we love work with the best open source ecommerce framework.

We hope you could continue reviewing our plugin code and if you want to collaborate we really appreciate it.

Kind regards,
Diego D'amico.

**Comment by Zales0123** [comment]
Hello Diego! 

Thank you very much for your reply, I'm happy that we understand each other, of course, no hard feelings 😄It's nice to hear that you enjoy working with Sylius, I've seen you created some more plugins, I would love to review them (along with this one) and give you some feedback/comment, I hope I'll find some time for that next week.

One more time, thank you for the reply and have a good weekend! :)
