### ISSUE TITLE
Exception during template rendering

### ISSUE THREAD

**Issue by alexweggs** [odiseoteam/SyliusReportPlugin#11]
Hi,

After my report creation, i got this excepetion : 

Twig\Error\RuntimeError:
An exception has been thrown during the rendering of a template ("[Syntax Error] line 0, col 7: Error: Expected known function, got 'DATE'").

  at vendor/odiseoteam/sylius-report-plugin/src/Resources/views/show.html.twig:64

Any information to debug that ?

Thanks a lot !

**Comment by songecko** [comment]
Hi @alexweggs, did you add the DoctrineExtensions settings like the README explains? 

```yml
doctrine:
    orm:
        # ...
        dql:
            datetime_functions:
                date: DoctrineExtensions\Query\Mysql\Date
                month: DoctrineExtensions\Query\Mysql\Month
                year: DoctrineExtensions\Query\Mysql\Year
            numeric_functions:
                round: DoctrineExtensions\Query\Mysql\Round
`
