### ISSUE TITLE
Datas does not gather well when yearly period time is defined

### ISSUE THREAD

**Issue by MathieuMaes182** [odiseoteam/SyliusReportPlugin#24]
It appears that when using the yearly period time format, datas are still displayed according to their months.

I've been creating a PR that fix the problem: 
- by setting month and day to 1 and 1 by default if you choose the yearly period (those ones are not relevant when datas are displayed by years)
- and by using the DATE_FORMAT doctrine function (instead of DATE) (need to be import by the user in his doctrine.yaml file). The date format is passed as a parameter of the query builder. I've defined the three formats in the DataFetcher\Data class as constants, and created a function that returns the format according to what it receives in the configuration.

The two screenshots here shows how the plugin is working now: 
![image](https://github.com/odiseoteam/SyliusReportPlugin/assets/82578062/97428fc6-2412-4d34-b326-41ab05329efa)
![image](https://github.com/odiseoteam/SyliusReportPlugin/assets/82578062/9cd703b1-a723-463c-ba11-2560d7895c28)

And here find how it works with the fixes:
![image](https://github.com/odiseoteam/SyliusReportPlugin/assets/82578062/aae1dc4c-7db2-426c-b7a7-981115185fcb)
![image](https://github.com/odiseoteam/SyliusReportPlugin/assets/82578062/e58d7317-5352-4984-a3a2-6f7a7b51aaf4)

Here is the link to the PR: https://github.com/odiseoteam/SyliusReportPlugin/pull/23

I remain available here to answer any questions or to discuss the choices I've made.

**Comment by Kblua** [comment]
@bigboss86  
Indeed, I also have the problem on my client project, can you please review this PR and merge it.

**Comment by bigboss86** [comment]
Merged! Thanks!

**Comment by Kblua** [comment]
Thank you very ! You've done a great job !
