### ISSUE TITLE
Class 'Sylius\Component\Order\Model\OrderInterface' does not exist

### ISSUE THREAD

**Issue by vasilvestre** [odiseoteam/SyliusReportPlugin#3]
Hello,

Following the instructions I got this error when I choose to access a report

More informations :

This happen in dataFetcher, when they try to get metadata of OrderInterface class. The message mean that the class can't be found. Putting my own class in APpBundle\Entity work.

**Comment by odiseoteam** [comment]
Hi @vasilvestre. new version has been released. Please, feel free to open a new issue if you have problems again.

**Comment by vasilvestre** [comment]
> Hi @vasilvestre. new version has been released. Please, feel free to open a new issue if you have problems again.

Really nice ! I'm upgrading sylius and install this soon :) Great work for sure !
