### ISSUE TITLE
odiseo_sylius_report.model.report.class param is missing

### ISSUE THREAD

**Issue by pierre-H** [odiseoteam/SyliusReportPlugin#6]
Hello,

Thank you for your work !

With a fresh install of this plugin with Sylius 1.4.3 and Symfony 4.2.7, there is this error : `You have requested a non-existent parameter "odiseo_sylius_report.model.report.class"`.

Any idea how to fix that ? I could add a custom parameter but that's not really clean ...

**Comment by songecko** [comment]
Hello @pierre-H . Yes, like the Readme explain you need to put the plugin bundle before the SyliusResourceBundle on the bundles.php.

Regards.

**Comment by pierre-H** [comment]
Ok ! Thank you for your answer !
