### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by pierre-H** [odiseoteam/SyliusReportPlugin#8]
Hello,

When do you plan to release the new version ?

Thank you !

**Comment by songecko** [comment]
@pierre-H  We expect the next week :D

**Comment by songecko** [comment]
Sorry about that. We are delayed with this. I promise we will uplodad the new version soon.

**Comment by odiseoteam** [comment]
Hi @pierre-H , new version has been released. Please, feel free to open a new issue if you have problems.
